[package]
name = "examples_rclrs_message_demo"
version = "0.4.1"
authors = ["Nikolai Morin <nnmmgit@gmail.com>"]
edition = "2021"

[[bin]]
name = "message_demo"
path = "src/message_demo.rs"

[dependencies]
anyhow = {version = "1", features = ["backtrace"]}

[dependencies.rclrs]
version = "0.4"

[dependencies.rosidl_runtime_rs]
version = "0.4"

[dependencies.rclrs_example_msgs]
version = "0.4"
features = ["serde"]

[dependencies.serde_json]
version = "1.0"
